### ISSUE TITLE
Exception when using the new CryptoExchange.Net version 6.2.0

### ISSUE THREAD

**Issue by danielhw2** [ridicoulous/Bitmex.NET#48]
Hello.

Can't update the CryptoExchange.Net to version 6.2.0, some Exceptions accours when using the solution.

Bitmex.Net ver 3.0.0
CryptoExchange.Net 6.2.0

**Comment by ridicoulous** [comment]
Hello. 

Right now this library uses older version of CryptoExchange: [6.1.4](https://github.com/ridicoulous/Bitmex.Net/blob/9aba3dc96d49ef0f1654d4cd8b14c0ff34e7152e/Bitmex.Net/Bitmex.Net.Client.csproj#L24) 
Feel free to update it and create pull request, or wait when one of contributors make it. We does not have enough time for maintaining of library because of russia invasion, we have other more priority tasks. 
Thank you, your contributing are always welcome
